ifeq ($(CONFIG_LINUX), y)
obj-$(CONFIG_SOFTMMU) += common.o
obj-$(CONFIG_PCI) += pci.o pci-quirks.o
obj-$(CONFIG_SOFTMMU) += platform.o
obj-$(CONFIG_SOFTMMU) += calxeda-xgmac.o

obj-$(CONFIG_LIBQEMU) += common.o
obj-$(CONFIG_LIBQEMU) += platform.o
obj-$(CONFIG_LIBQEMU) += calxeda-xgmac.o
endif
