obj-helper-y = dsp_helper.o op_helper.o lmi_helper.o helper.o msa_helper.o
obj-y += translate.o cpu.o
obj-y += gdbstub.o mips-semi.o
obj-$(CONFIG_SOFTMMU) += machine.o
obj-$(CONFIG_KVM) += kvm.o
obj-y += $(obj-helper-y)
