obj-helper-y = helper.o 
obj-helper-y += int_helper.o fpu_helper.o cc_helper.o mem_helper.o misc_helper.o
obj-helper-$(CONFIG_SOFTMMU) += mmu_helper.o
obj-y += translate.o cpu.o interrupt.o
obj-y += gdbstub.o
obj-$(CONFIG_SOFTMMU) += machine.o ioinst.o arch_dump.o
obj-$(CONFIG_KVM) += kvm.o
obj-y += $(obj-helper-y)
